config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  resources :books

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book =  Book.where(id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/show.html.erb
<div id="page-wrapper" style="min-height: 353px;">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Book details</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= image_tag(@book.first.image.url(:medium)) %>
    </div>
  </div>

  <div class="row top-buffer">
    <div class="col-md-12">
      <strong>Title : </strong> <%= @book.first.title %>
    </div>
  </div>

  <div class="row top-buffer">
    <div class="col-md-12">
      <strong>Author : </strong> <%= @book.first.author %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Books</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover responsive no-wrap" id="books">
              <thead>
                <tr>
                  <th></th>
                  <th>Book Title</th>
                  <th>Author</th>
                </tr>
              </thead>
              <tbody>
                <% @books.each do |book| %>
                  <tr class="odd gradeX">
                    <td class="center">
                      <%= image_tag(book.image.url(:thumb)) %>
                    </td>
                    <td class="center">
                      <%= link_to book.title, book_path(book) %>
                    </td>
                    <td class="center">
                      <%= book.author %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <%= link_to "Books", root_path, :class => "navbar-brand" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageBooks</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="wrapper">
      <%= render :partial => 'layouts/navigation' %>
      <%= yield %>
    </div>
  </body>
</html>